name: Deploy portfolio-builder
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/portfolio-builder/**'
      - '.github/workflows/deploy-portfolio-builder.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install and Build
        working-directory: ./apps/portfolio-builder
        run: |
          bun install
          bun run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "REPLACE_WITH_PROJECT_ID"
          channelId: live
          target: portfolio-builder
